### ISSUE TITLE
Request codes must be unique. File picker=3, Folder picker=0, Storage access=0, Create file=4

### ISSUE THREAD

**Issue by naveen-nuveda** [anggrayudi/SimpleStorage#93] opened 2022-07-18 11:30 UTC
Library version: 1.3.0
OS version: Android 11
Device model: Realme X2
**Describe the bug**
Caused by java.lang.IllegalArgumentException
Request codes must be unique. File picker=3, Folder picker=0, Storage access=0, Create file=4
com.anggrayudi.storage.SimpleStorage.checkRequestCode (SimpleStorage.java:101)
com.anggrayudi.storage.SimpleStorage.setRequestCodeFolderPicker (SimpleStorage.java:2)
com.anggrayudi.storage.SimpleStorage.onRestoreInstanceState (SimpleStorage.java:58)

**To Reproduce**
It is working on some phones and not working on some other phones

**Stacktrace**
[If applicable]

**Comment by anggrayudi** [comment] 2022-07-18 21:02
This is not a bug. Request code must be unique, but your folder picker and storage access request codes are the same. Try using different request code. If the error still persists, try to change the request code via `SimpleStorage#requestCode...`. If you're using `SimpleStorageHelper`, just access it via `SimpleStorageHelper#storage#requestCode...`

**Comment by anggrayudi** [comment] 2022-07-23 10:37
Fixed in [v1.4.1](https://github.com/anggrayudi/SimpleStorage/releases/tag/1.4.1)

**Closed by anggrayudi** 2022-07-23 10:37 UTC
Labels: bug
